import {
  pgTable,
  uuid,
  varchar,
  json,
  timestamp,
  boolean,
  integer,
} from "drizzle-orm/pg-core";
import type { InferSelectModel } from "drizzle-orm";

const normalMessageDbObject = {
  id: uuid("id").primaryKey().notNull().defaultRandom(),
  // user prompt
  prompt: varchar("prompt").notNull(),
  // response is the string generated by the llm
  response: varchar("response").notNull(),
  // location will be either "chat/completions" or "completions"
  // this is to make sure which of our 2 APIs is being used to generate response
  location: varchar("location").notNull(),
  model: varchar("model").notNull(),
  stream: boolean("stream").notNull(),
  createdAt: timestamp("createdAt").notNull(),
  nonce: varchar("nonce"),
  hash: varchar("hash"),
};

export const message = pgTable("Message", normalMessageDbObject);

export type Message = InferSelectModel<typeof message>;

export const nexusMessage = pgTable("NexusMessage", normalMessageDbObject);

export type NexusMessage = InferSelectModel<typeof nexusMessage>;

export const solanaMessage = pgTable("SolanaMessage", normalMessageDbObject);

export type SolanaMessage = InferSelectModel<typeof solanaMessage>;

// just for reference. this is what the json will contain.
type toolsCalled = {
  toolName: string;
  toolResponse: any;
}[];

export const toolTracking = pgTable("ToolTracking", {
  id: uuid("id").primaryKey().notNull().defaultRandom(),
  userPrompt: varchar("userPrompt").notNull(),
  aiResponse: json("aiResponse").notNull(),
  toolsCalled: json("toolsCalled").array().notNull(),
  toolsCalledNames: json("toolsCalledNames").array().notNull(),
  createdAt: timestamp("createdAt").notNull(),
});

export type ToolTracking = InferSelectModel<typeof toolTracking>;

export const consumerTable = pgTable("ConsumerTable", {
  id: uuid("id").primaryKey().notNull().defaultRandom(),
  apiConsumerName: varchar("apiConsumerName").notNull(),
  apiKey: varchar("apiKey").notNull().unique(),
  mode: varchar("mode").notNull(),
  tableName: varchar("tableName").notNull(),
  description: varchar("description").notNull(),
  createdAt: timestamp("createdAt").notNull(),
  rate_limit: integer("rate_limit").notNull().default(10),
});

export type ConsumerTable = InferSelectModel<typeof consumerTable>;

export type ConsumerEnumType = "SENTIENT" | "NEXUS" | "SOLANA_HACKATHON";
