import {
  pgTable,
  uuid,
  varchar,
  json,
  timestamp,
  boolean,
} from "drizzle-orm/pg-core";
import type { InferSelectModel } from "drizzle-orm";
export const message = pgTable("Message", {
  id: uuid("id").primaryKey().notNull().defaultRandom(),
  // user prompt
  prompt: varchar("prompt").notNull(),
  // response is the string generated by the llm
  response: varchar("response").notNull(),
  // location will be either "chat/completions" or "completions"
  // this is to make sure which of our 2 APIs is being used to generate response
  location: varchar("location").notNull(),
  model: varchar("model").notNull(),
  stream: boolean("stream").notNull(),
  createdAt: timestamp("createdAt").notNull(),
});

export type Message = InferSelectModel<typeof message>;

// just for reference. this is what the json will contain.
type toolsCalled = {
  toolName: string;
  toolResponse: any;
}[];

export const toolTracking = pgTable("ToolTracking", {
  id: uuid("id").primaryKey().notNull().defaultRandom(),
  userPrompt: varchar("userPrompt").notNull(),
  aiResponse: json("aiResponse").notNull(),
  toolsCalled: json("toolsCalled").array().notNull(),
  toolsCalledNames: json("toolsCalledNames").array().notNull(),
  createdAt: timestamp("createdAt").notNull(),
});

export type ToolTracking = InferSelectModel<typeof toolTracking>;
