import { pgTable, uuid, varchar, json, timestamp, boolean } from "drizzle-orm/pg-core";
import type { InferSelectModel } from "drizzle-orm";
export const message = pgTable("Message", {
  id: uuid("id").primaryKey().notNull().defaultRandom(),
  // user prompt
  prompt: varchar("prompt").notNull(),
  // response is the string generated by the llm
  response: varchar("response").notNull(),
  // location will be either "chat/completions" or "completions"
  // this is to make sure which of our 2 APIs is being used to generate response
  location: varchar("location").notNull(),
  model: varchar("model").notNull(),
  stream: boolean("stream").notNull(),
  createdAt: timestamp("createdAt").notNull(),
});

export type Message = InferSelectModel<typeof message>;
