"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { InstallPrompt } from "@/components/install-prompt";
import VerifyPageHeader from "./verify-header";
import { User } from "next-auth";

export default function OutputVerifier({ user }: { user?: User }) {
  const [userOutput, setUserOutput] = useState("");
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  async function handleVerify() {
    setLoading(true);
    setResult(null);
    try {
      const res = await fetch("/api/verify-output", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ output: userOutput }),
      });
      const data = await res.json();
      console.log(data)
      setResult(data);
    } catch (err) {
      setResult({ success: false, error: "Verification failed. Try again." });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen w-full bg-background">
      <InstallPrompt />
      <VerifyPageHeader user={user} />

      <div className="max-w-2xl mx-auto mt-10 p-6">
        <h1 className="text-2xl font-semibold mb-4">Verify LLM Output</h1>
        <p className="text-sm text-gray-500 mb-2">
          Paste the full response (including the 🔒 Output ID) shown to you in
          the chat interface.
        </p>
        <textarea
          value={userOutput}
          onChange={(e) => setUserOutput(e.target.value)}
          className="w-full h-60 p-4 border rounded-xl text-sm font-mono"
          placeholder="Paste output here..."
        />
        <Button
          onClick={handleVerify}
          className="mt-4 w-full"
          disabled={loading}
        >
          {loading ? "Verifying..." : "Verify Output"}
        </Button>

        {result && (
          <Card className="mt-6">
            <CardContent className="p-4">
              {result.success ? (
                <p className="text-green-600 font-medium">
                  ✅ Verified: This output was generated by Javin
                </p>
              ) : (
                <p className="text-red-600 font-medium">
                  ❌ Not Verified:{" "}
                  {result.error || "Output may have been altered."}
                </p>
              )}
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
